[build]
    command = "npm install"
    functions = "functions"
[functions]
    node_bundler = "esbuild"
[[redirects]]
    from = "/*"
    to = "/.netlify/functions/server/*"
    force = false
    status = 200
[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Headers = "Content-Type"
        Access-Control-Allow-Methods = "GET, HEAD, PUT, POST, OPTION"