[build]
    command = "npm install && npm run build"
    publish = "dist/"
    functions = "functions"
[functions]
    node_bundler = "esbuild"
[headers]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, HEAD, PUT, POST, OPTION"